---
name: "gradle"
github: "jenkinsci/gradle-plugin"
paths:
  - "org/jenkins-ci/plugins/gradle-configuration-maven-extension"
developers:
  - "gbois"
  - "wolfs"
  - "avenderov"
  - "facewindu"
  - "guylabs"
  - "sflorea"
  - "welandaz"
  - "atual"
