---
name: "spring-config"
github: &GH "jenkinsci/spring-config-plugin"
issues:
  - github: *GH
paths:
  - "io/jenkins/plugins/spring-config"
developers:
  - "topikachu"
cd:
  enabled: true
  exclusive: false
