---
name: "configuration-as-code-support"
github: &gh "jenkinsci/configuration-as-code-plugin"
issues:
  - github: *gh
  - jira: '23170'  # configuration-as-code-plugin
paths:
  - "io/jenkins/configuration-as-code/configuration-as-code-support"
developers:
  - ldap: "praqma"
  - ldap: "jetersen"
    github: "jetersen"
  - github: "ReleasePraqma"
  - github: "MadsNielsen"
  - github: "buep"
  - github: "oleg-nenashev"
  - github: "timja"
  - github: "ewelinawilkosz"
security:
    contacts:
        jira: "jetersen"
repository_team: "configuration-as-code-plugin Developers"
additional_github_teams:
  - team: "jcasc-compatibility-reviewers"
    role: "Read"
  - team: "configuration-as-code-devtools-project-team"
    role: "Triage"
