---
name: "config-file-provider"
github: "jenkinsci/config-file-provider-plugin"
issues:
  - jira: '16140'  # config-file-provider-plugin
paths:
  - "org/jenkins-ci/plugins/config-file-provider"
cd:
    enabled: true
developers:
  - ldap: "imod"
  - ldap: "egutierrez"
  - ldap: "alecharp"
    github: "alecharp"
  - ldap: "batmat"
    github: "batmat"
  - ldap: "mramonleon"
  - ldap: "rsandell"
    github: "rsandell"
  - ldap: "jm_meessen"
  - github: "jmMeessen"
  - github: "varyvol"
  - github: "MRamonLeon"
security:
    contacts:
        jira: "cloudbees_security_members"
repository_team: "config-file-provider-plugin Developers"
