---
name: "blueocean-config"
github: "jenkinsci/blueocean-plugin"
issues:
- jira: '21481' # blueocean-plugin
paths:
- "io/jenkins/blueocean/blueocean-config"
developers:
- "michaelneale"
- "vivek"
- "kzantow"
- "davidbees"
- "richbg"
- "carroll"
- "dnusbaum"
- "jtaboada"
- "kshultz"
- "bitwiseman"
- "olamy"
- "tscherler"
security:
  contacts:
    jira: "cloudbees_security_members"
