---
name: "script-security"
github: &gh "jenkinsci/script-security-plugin"
issues:
  - github: *gh
paths:
  - "org/jenkins-ci/plugins/script-security"
cd:
  enabled: true
developers:
  - "jglick"
  - "kohsuke"
  - "abayer"
  - "rsandell"
  - "dnusbaum"
  - "carroll"
  - "bitwiseman"
  - "kshultz"
security:
  contacts:
    jira: "cloudbees_security_members"
