---
name: "configuration-as-code"
github: &GH jenkinsci/configuration-as-code-plugin
paths:
- "org/jenkins-ci/plugins/configuration-as-code"
- "io/jenkins/configuration-as-code"
developers:
- "praqma"
- "jetersen"
- "oleg_nenashev"
- "timja"
security:
  contacts:
    jira: "jetersen"
issues:
  - github: *GH
  - jira: 23170 # configuration-as-code-plugin
    report: no
