---
name: "script-security"
github: "jenkinsci/script-security-plugin"
paths:
- "org/jenkins-ci/plugins/script-security"
developers:
- "jglick"
- "kohsuke"
- "abayer"
- "svanoort"
- "rsandell"
- "dnusbaum"
