---
name: "crowdstrike-security"
github: &GH "jenkinsci/crowdstrike-security-plugin"
paths:
- "io/jenkins/plugins/crowdstrike-security"
developers:
- "crwd_etatarevic"
- "crwdsmullz"
- "crwdlemos"
- "crwdharshitac"
issues:
  - github: *GH
