---
name: "azure-publishersettings-credentials"
github: "jenkinsci/azure-publishersettings-credentials-plugin"
issues:
- jira: '21220' # azure-publishersettings-credentials-plugin
paths:
- "org/jenkins-ci/plugins/azure-publishersettings-credentials"
developers:
- "batmat"
- "markwm"
- "@cloudbees-developers"
security:
  contacts:
    jira: "cloudbees_security_members"
