---
name: "aws-global-configuration"
github: "jenkinsci/aws-global-configuration-plugin"
issues:
- jira: '23929' # aws-global-configuration-plugin
paths:
- "io/jenkins/plugins/aws-global-configuration"
developers:
- "jglick"
- "csanchez"
- "oleg_nenashev"
- "ifernandezcalvo"
- "@cloudbees-developers"
security:
  contacts:
    jira: "cloudbees_security_members"
