---
name: "hp-application-automation-tools-plugin"
github: "jenkinsci/hpe-application-automation-tools-plugin"
paths:
- "org/jenkins-ci/plugins/hp-application-automation-tools-plugin"
developers:
- "mrman"
- "ofirshaked"
- "shimor"
- "yafim_kazak"