---
name: "jobConfigHistory"
github: &gh "jenkinsci/job-config-history-plugin"
issues:
  - github: *gh
paths:
  - "org/jenkins-ci/plugins/jobConfigHistory"
developers:
  - "stefan_spieker"
cd:
  enabled: true
