---
name: "generic-environment-filters"
github: &GH "jenkinsci/generic-environment-filters-plugin"
issues:
  - github: *GH
paths:
  - "io/jenkins/plugins/generic-environment-filters"
developers:
  - "@security"
cd:
  enabled: true
communityPluginMaintainers: false
