---
name: "jobConfigHistory"
github: "jenkinsci/job-config-history-plugin"
issues:
- jira: '15683' # jobconfighistory-plugin
paths:
- "org/jenkins-ci/plugins/jobConfigHistory"
developers:
- "NotMyFault"
cd:
  enabled: true
