---
name: "config-file-provider"
github: "jenkinsci/config-file-provider-plugin"
issues:
- jira: '16140' # config-file-provider-plugin
paths:
- "org/jenkins-ci/plugins/config-file-provider"
developers:
- "imod"
- "egutierrez"
- "alecharp"
- "batmat"
- "mramonleon"
- "rsandell"
- "jm_meessen"
security:
  contacts:
    jira: "cloudbees_security_members"
