---
name: "script-security"
github: "jenkinsci/script-security-plugin"
issues:
- jira: '18520' # script-security-plugin
paths:
- "org/jenkins-ci/plugins/script-security"
cd:
  enabled: true
developers:
- "jglick"
- "kohsuke"
- "abayer"
- "svanoort"
- "rsandell"
- "dnusbaum"
- "carroll"
- "bitwiseman"
- "kshultz"
security:
  contacts:
    jira: "cloudbees_security_members"
