---
name: "hp-application-automation-tools-plugin"
github: &gh "jenkinsci/hpe-application-automation-tools-plugin"
issues:
  - github: *gh
paths:
  - "org/jenkins-ci/plugins/hp-application-automation-tools-plugin"
developers:
  - "buzas"
  - "andreibangau"
  - "abarbura"
  - "tudordecea"
