name: Hosting checker
on:
  issues:
    types:
      - opened
      - edited
jobs:
  hosting:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'hosting-request')
    steps:
      - uses: actions/checkout@v6
        with:
          ref: 'master'
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package -Dspotbugs.skip
      - name: Run hosting checker
        run: |
          java -jar target/repository-permissions-updater-1.0-SNAPSHOT-bin/repository-permissions-updater-1.0-SNAPSHOT.jar check-hosting ${{ github.event.issue.number }}
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
